### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by RobCherry** [bitly/oauth2_proxy#216]
Appears to have been caused by https://github.com/mreiferson/go-options/pull/4.

```
panic: interface conversion: *main.StringArray is not flag.Getter: missing method Get

goroutine 1 [running]:
github.com/mreiferson/go-options.Resolve(0x8692c0, 0xc8200c8580, 0xc820037ee8, 0xc82008af90)
	/go/src/github.com/mreiferson/go-options/options.go:86 +0xe7c
main.main()
	/go/src/github.com/bitly/oauth2_proxy/main.go:93 +0x15e6
```

**Comment by mreiferson** [comment]
whooops

**Comment by mreiferson** [comment]
You should probably use `godep` to build the binary, though, so you don't pickup random changes to master in its dependencies.

**Comment by RobCherry** [comment]
@mreiferson Yeah, using https://github.com/pote/gpm I was able to get it building again.  I am going to update the issue to reflect that this project will not run with the latest versions of https://github.com/mreiferson/go-options.
