### ISSUE TITLE
provider ignored?

### ISSUE THREAD

**Issue by xmunoz** [bitly/oauth2_proxy#267]
I'm trying to set up oauth2_proxy with gitlab (self-hosted) as my provider. Unfortunately, it doesn't appear that my provider selection is honored. Here is my configuration file:

```
provider = "gitlab"
upstreams = "http://127.0.0.1:8888"
login_url = "https://gitlab.mydomain.com/oauth/authorize"
redeem_url = "https://gitlab.mydomain.com/oauth/token"
validate_url = "https://gitlab.mydomain.com/api/v3/user"
client_id = "LONGCLIENTIDSTRING"
client_secret = "LONGCLIENTSECRETSTRINGSHHHHH"
cookie_secret = "RANDOM"
redirect_url = "https://app.mydomain.com/oauth2/callback"
cookie_secure = true
scope = "api"
```

Unfortunately, the login screen still asks me to "Login with a Google Account". The login url redirection to gitlab works, but the flow fails on the redeem step. Here is the log output:

```
./oauth2_proxy -config=/etc/oauth2_proxy.cfg
2016/06/14 18:00:28 oauthproxy.go:90: mapping path "/" => upstream "http://127.0.0.1:8888"
2016/06/14 18:00:28 oauthproxy.go:106: OauthProxy configured for Google Client ID: LONGCLIENTIDSTRING
2016/06/14 18:00:28 oauthproxy.go:116: Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
2016/06/14 18:00:28 http.go:45: HTTP: listening on 127.0.0.1:4180
2016/06/14 18:01:14 oauthproxy.go:455: 127.0.0.1:52600 ("130.73.75.72") Cookie "_oauth2_proxy" not present
130.73.75.72 - - [14/Jun/2016:18:01:14 +0200] rubberband.zib.de:443 GET - "/" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36" 403 2244 0.001
130.73.75.72 - - [14/Jun/2016:18:01:49 +0200] rubberband.zib.de:443 GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36" 302 286 0.000
2016/06/14 18:01:49 server.go:1775: http: panic serving 127.0.0.1:52604: runtime error: index out of range
goroutine 9 [running]:
net/http.funcÂ·011()
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/bitly/oauth2_proxy/providers.emailFromIdToken(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jehiah/projects/gopath/src/github.com/bitly/oauth2_proxy/providers/google.go:53 +0x451
github.com/bitly/oauth2_proxy/providers.(*GoogleProvider).Redeem(0xc2080334e0, 0xc208090cf0, 0x2d, 0xc20801143a, 0x40, 0x0, 0x0, 0x0)
        /Users/jehiah/projects/gopath/src/github.com/bitly/oauth2_proxy/providers/google.go:129 +0x1071
main.(*OauthProxy).redeemCode(0xc20806c500, 0xc20801f8e0, 0x15, 0xc20801143a, 0x40, 0x1, 0x0, 0x0)
        /Users/jehiah/projects/tmp_build/src/github.com/bitly/oauth2_proxy/oauthproxy.go:184 +0x1ce
main.(*OauthProxy).OauthCallback(0xc20806c500, 0x7f3e61e59940, 0xc208035540, 0xc20803d1e0)
        /Users/jehiah/projects/tmp_build/src/github.com/bitly/oauth2_proxy/oauthproxy.go:421 +0x25a
main.(*OauthProxy).ServeHTTP(0xc20806c500, 0x7f3e61e59940, 0xc208035540, 0xc20803d1e0)
        /Users/jehiah/projects/tmp_build/src/github.com/bitly/oauth2_proxy/oauthproxy.go:373 +0x32a
main.loggingHandler.ServeHTTP(0x7f3e61e57db0, 0xc208036008, 0x7f3e61e58670, 0xc20806c500, 0x1, 0x7f3e61e59908, 0xc208044b40, 0xc20803d1e0)
        /Users/jehiah/projects/tmp_build/src/github.com/bitly/oauth2_proxy/logging_handler.go:82 +0x153
main.(*loggingHandler).ServeHTTP(0xc20800bdd0, 0x7f3e61e59908, 0xc208044b40, 0xc20803d1e0)
        <autogenerated>:13 +0xbe
net/http.serverHandler.ServeHTTP(0xc20805a3c0, 0x7f3e61e59908, 0xc208044b40, 0xc20803d1e0)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208044a00)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e

```
How can I tell oauth2_proxy to not use google?

**Comment by xmunoz** [comment]
I was able to get this library working by [changing the default provider](https://github.com/xmunoz/oauth2_proxy/commit/3f420880bb627d53206a57805da12189503d170b). Maybe the binary that I downloaded is just old...

**Comment by 0815fox** [comment]
I just bumped into the same issue... The last release is a year old and does not contain gitlab provider. Do you have a hint for me on how to build project?

**Comment by xmunoz** [comment]
Yep. You should just be able to use `go get github.com/bitly/oauth2_proxy`. This will put the source in your $GOPATH. Then simply `go install github.com/bitly/oauth2_proxy`.

**Comment by 0815fox** [comment]
Thank you!
